M48
; DRILL file {KiCad 8.0.5} date 2024-10-06T15:25:16+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-06T15:25:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.5979Y-4.0827
X4.5979Y-4.3102
X4.5986Y-3.6745
X4.5986Y-3.9021
T2
X6.0719Y-4.5713
X6.3869Y-4.5713
M30
